// Data loading with fallback (SPEC §5.2). Uses only fetch, AbortController
// and timers, so Node tests can run it with an injected fetch.

import { parseCSV } from "./csv.js";
import { buildModel, csvUrl, MODEL_VERSION, TABS, TAB_NAMES } from "./model.js";

// "sample" for ?forras=minta, "snapshot" while the Sheet is not configured,
// otherwise "live".
export function pickMode(config, search) {
  if (new URLSearchParams(search).get("forras") === "minta") return "sample";
  const configured = config.PUB_ID && TABS.every((tab) => config.GIDS && config.GIDS[tab]);
  return configured ? "live" : "snapshot";
}

// Resolves to { model, origin, fallbackReason? }. Rejects only when the
// snapshot cannot be loaded either.
export async function loadData(config, { mode, fetch = globalThis.fetch, now = () => new Date() } = {}) {
  // The snapshot is requested right away, alongside the CSVs, so that a failed
  // live load switches to it without a second wait: "Betöltés…" stays at most
  // about TIMEOUT_MS (SPEC 1.1 §4.7). Settled into a value so an unused
  // failure is never an unhandled rejection.
  const snapshot = fetchSnapshot(config, fetch).then(
    (model) => ({ model }),
    (error) => ({ error }),
  );
  let fallbackReason;
  if (mode === "live" || mode === "sample") {
    try {
      const tables = await fetchTables(config, mode, fetch);
      const result = buildModel(tables, { source: mode === "live" ? "sheet" : "sample", now: now() });
      if (result.ok) return { model: result.model, origin: mode };
      fallbackReason = result.fatal.join("; ");
    } catch (err) {
      fallbackReason = err.message;
    }
  }
  const { model, error } = await snapshot;
  if (error) throw new Error(fallbackReason === undefined ? error.message : `${fallbackReason}; ${error.message}`);
  return fallbackReason === undefined ? { model, origin: "snapshot" } : { model, origin: "snapshot", fallbackReason };
}

// Runs fn(signal) and aborts it after ms. On any failure the remaining
// requests are aborted too.
async function withTimeout(ms, fn) {
  const controller = new AbortController();
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, ms);
  try {
    return await fn(controller.signal);
  } catch (err) {
    controller.abort();
    if (timedOut) throw new Error(`timeout after ${ms} ms`);
    throw err;
  } finally {
    clearTimeout(timer);
  }
}

// The five CSVs in parallel, each with its own timeout (SPEC 1.1 §2.1). When
// one fails, the others are aborted.
async function fetchTables(config, mode, fetch) {
  const url = (tab) => (mode === "live" ? csvUrl(config, tab) : `${config.SAMPLE_BASE}${tab}.csv`);
  const stop = new AbortController();
  const fetchTab = (tab) =>
    withTimeout(config.TIMEOUT_MS, async (signal) => {
      const res = await fetch(url(tab), { signal: anySignal([signal, stop.signal]), cache: "no-store" });
      if (!res.ok) throw new Error(`${TAB_NAMES[tab]}: HTTP ${res.status}`);
      const text = await res.text();
      // Google answers with an HTML sign-in or error page when a tab is not published.
      if (text.trimStart().startsWith("<")) throw new Error(`${TAB_NAMES[tab]}: HTML response instead of CSV`);
      return text;
    }).catch((err) => {
      if (err.message.startsWith("timeout")) err.message = `${TAB_NAMES[tab]}: ${err.message}`;
      throw err;
    });
  try {
    const texts = await Promise.all(TABS.map(fetchTab));
    return Object.fromEntries(TABS.map((tab, i) => [tab, parseCSV(texts[i])]));
  } catch (err) {
    stop.abort();
    throw err;
  }
}

// A signal that aborts when any of the given signals does.
function anySignal(signals) {
  const controller = new AbortController();
  for (const signal of signals) {
    if (signal.aborted) controller.abort();
    else signal.addEventListener("abort", () => controller.abort(), { once: true });
  }
  return controller.signal;
}

function fetchSnapshot(config, fetch) {
  return withTimeout(config.TIMEOUT_MS, async (signal) => {
    const res = await fetch(config.SNAPSHOT_URL, { signal, cache: "no-cache" });
    if (!res.ok) throw new Error(`snapshot: HTTP ${res.status}`);
    const data = await res.json();
    if (!isValidSnapshot(data)) throw new Error("snapshot: unexpected format");
    return data;
  });
}

// The snapshot is generated by scripts/snapshot.mjs, but a hand-edited or
// corrupted file must lead to the fatal state rather than a half-rendered page.
function isValidSnapshot(data) {
  const str = (v) => typeof v === "string";
  const top =
    data && data.version === MODEL_VERSION && str(data.generatedAt) && !Number.isNaN(Date.parse(data.generatedAt)) &&
    typeof data.settings === "object" && data.settings !== null && Object.values(data.settings).every(str) &&
    Array.isArray(data.days) && Array.isArray(data.periods) && data.periods.length > 0 &&
    Array.isArray(data.classes) && data.classes.length > 0 && data.classes.every(str) &&
    Array.isArray(data.activities) && Array.isArray(data.items) && Array.isArray(data.issues);
  if (!top) return false;
  const days = new Set(data.days.map((d) => d && d.key));
  const periods = new Set(data.periods.map((p) => p && p.n));
  const activities = new Set(data.activities.map((a) => a && str(a.name) && str(a.color) && str(a.tint) && a.id));
  return data.items.every(
    (s) =>
      s && days.has(s.day) && periods.has(s.first) && periods.has(s.last) && s.last >= s.first &&
      activities.has(s.activityId) && str(s.activity) && str(s.teacher) && str(s.room) && str(s.note) &&
      Array.isArray(s.targets) && typeof s.uncertain === "boolean" && Number.isFinite(s.sheetRow),
  );
}
